class ApiConstant {
  static const String baseUrl = 'https://shopdunk.com';
  static const String categories = '/api/categories';
  static const String news = '/api/news-category';
  static const String products = '/api/products/get-category-featured-products/';
  static const String searchProducts = '/api/search-products';
  static const String token = '/token';
  static const String register = '/api/customers/register';
  static const String relatedNews = '/api/get-related-entities/';
  static const String newsGroup = '/api/news-group';
  static const String productsGroup = '/api/products-category';
  static const String newsComments = '/api/add-comment';
  static const String topBanner = '/api/topics/156';
  static const String homeBanner = '/api/topics/6';
  static const String categoryBanner = '/api/topics/';
  static const String subCategory = '/api/category/';
  static const String footer = '/api/topics';
  static const String order = '/api/orders/customer/';
  static const String customer = '/api/customers/';
  static const String info = '/api/customers/info';
  static const String rating = '/api/customers/ratings/';
  static const String address = '/api/customers/address';
  static const String updateInfo = '/api/customers/update-info';
  static const String productRating = '/api/products/';
  static const String state = '/api/customers/states';
  static const String mySystem = '/api/customers/filter-system?level=';
  static const String recovery = '/api/customers/password-recovery';
  static const String changePassword = '/api/customers/change-password';
}
